grep -src 'aapJ-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>aapJ-PRO-HLI
grep -src 'aapJ-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>aapJ-PRO-HLII
grep -src 'aapJ-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>aapJ-PRO-HLVI
grep -src 'aapJ-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>aapJ-PRO-LLI
grep -src 'aapJ-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>aapJ-PRO-LLIIxIII
grep -src 'aapJ-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>aapJ-PRO-LLIV
grep -src 'aapJ-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>aapJ-SYN
grep -src 'amt1-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>amt1-PRO-HLI
grep -src 'amt1-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>amt1-PRO-HLII
grep -src 'amt1-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>amt1-PRO-HLVI
grep -src 'amt1-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>amt1-PRO-LLI
grep -src 'amt1-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>amt1-PRO-LLIIxIII
grep -src 'amt1-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>amt1-PRO-LLIV
grep -src 'amt1-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>amt1-SYN
grep -src 'cynA-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>cynA-PRO-HLI
grep -src 'cynA-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>cynA-PRO-HLII
grep -src 'cynA-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>cynA-PRO-HLVI
grep -src 'cynA-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>cynA-SYN
grep -src 'fliY-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>fliY-SYN
grep -src 'focA-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>focA-PRO-HLVI
grep -src 'focA-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>focA-PRO-LLI
grep -src 'focA-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>focA-PRO-LLIIxIII
grep -src 'focA-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>focA-PRO-LLIV
grep -src 'focA-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>focA-SYN
grep -src 'glnQ-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>glnQ-PRO-HLI
grep -src 'glnQ-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>glnQ-PRO-HLII
grep -src 'glnQ-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>glnQ-PRO-HLVI
grep -src 'glnQ-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>glnQ-PRO-LLI
grep -src 'glnQ-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>glnQ-PRO-LLIIxIII
grep -src 'glnQ-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>glnQ-PRO-LLIV
grep -src 'glnQ-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>glnQ-SYN
grep -src 'gltJ-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>gltJ-PRO-HLI
grep -src 'gltJ-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>gltJ-PRO-HLII
grep -src 'gltJ-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>gltJ-PRO-HLVI
grep -src 'gltJ-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>gltJ-PRO-LLI
grep -src 'gltJ-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>gltJ-PRO-LLIIxIII
grep -src 'gltJ-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>gltJ-PRO-LLIV
grep -src 'gltJ-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>gltJ-SYN
grep -src 'livF-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livF-PRO-HLI
grep -src 'livF-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livF-PRO-HLII
grep -src 'livF-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livF-PRO-HLVI
grep -src 'livF-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livF-PRO-LLI
grep -src 'livF-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livF-PRO-LLIIxIII
grep -src 'livF-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livF-PRO-LLIV
grep -src 'livF-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livF-SYN
grep -src 'livH-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livH-PRO-HLI
grep -src 'livH-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livH-PRO-HLII
grep -src 'livH-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livH-PRO-HLVI
grep -src 'livH-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livH-PRO-LLI
grep -src 'livH-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livH-PRO-LLIIxIII
grep -src 'livH-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livH-PRO-LLIV
grep -src 'livH-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livH-SYN
grep -src 'livM-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>livM-SYN
grep -src 'metN2-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>metN2-PRO-HLI
grep -src 'metN2-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>metN2-PRO-HLII
grep -src 'metN2-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>metN2-PRO-LLI
grep -src 'metN2-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>metN2-PRO-LLIIxIII
grep -src 'metN2-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>metN2-PRO-LLIV
grep -src 'metN2-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>metN2-SYN
grep -src 'narB-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>narB-PRO-HLI
grep -src 'narB-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>narB-PRO-HLII
grep -src 'narB-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>narB-PRO-HLVI
grep -src 'narB-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>narB-PRO-LLI
grep -src 'narB-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>narB-SYN
grep -src 'natA-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>natA-PRO-HLII
grep -src 'natA-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>natA-SYN
grep -src 'natC-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>natC-SYN
grep -src 'nirA-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nirA-PRO-HLI
grep -src 'nirA-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nirA-PRO-HLII
grep -src 'nirA-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nirA-PRO-HLVI
grep -src 'nirA-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nirA-PRO-LLI
grep -src 'nirA-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nirA-PRO-LLIIxIII
grep -src 'nirA-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nirA-PRO-LLIV
grep -src 'nirA-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nirA-SYN
grep -src 'nrtA-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtA-SYN
grep -src 'nrtB-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtB-PRO-HLI
grep -src 'nrtB-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtB-PRO-HLII
grep -src 'nrtB-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtB-SYN
grep -src 'nrtC-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtC-SYN
grep -src 'nrtP-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtP-PRO-HLI
grep -src 'nrtP-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtP-PRO-HLII
grep -src 'nrtP-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtP-PRO-HLVI
grep -src 'nrtP-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtP-PRO-LLI
grep -src 'nrtP-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>nrtP-SYN
grep -src 'OocM-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>OocM-PRO-HLII
grep -src 'OocM-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>OocM-PRO-HLVI
grep -src 'OocM-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>OocM-PRO-LLI
grep -src 'OocM-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>OocM-PRO-LLIIxIII
grep -src 'TcyC-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>TcyC-PRO-LLIIxIII
grep -src 'TcyN-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>TcyN-PRO-HLI
grep -src 'TcyN-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>TcyN-PRO-HLII
grep -src 'TcyN-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>TcyN-PRO-LLI
grep -src 'TcyN-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>TcyN-SYN
grep -src 'urtA-PRO-HLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>urtA-PRO-HLI
grep -src 'urtA-PRO-HLII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>urtA-PRO-HLII
grep -src 'urtA-PRO-HLVI' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>urtA-PRO-HLVI
grep -src 'urtA-PRO-LLIx' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>urtA-PRO-LLI
grep -src 'urtA-PRO-LLIIxIII' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>urtA-PRO-LLIIxIII
grep -src 'urtA-PRO-LLIV' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>urtA-PRO-LLIV
grep -src 'urtA-SYN' /data/gpfs02/sjgao/Buce-2023-Tara/June-RESULTS-metaT/* | awk -F: '$NF+0 > -1'>urtA-SYN
